name: build & publish on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: 18.12.0
      - run: yarn install
      - run: yarn build
      # - run: yarn test
      - run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
