name: build & publish on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nwylynko/markdown-add-files@master
      - uses: nwylynko/markdown-code-runner@master
      - uses: actions/setup-node@master
        with:
          node-version: 16.13.2
      - run: yarn install
      - run: yarn build
      # - run: yarn test
      - run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
