name: auto fetch, build & publish

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18.15.0

      - run: pnpm fetchColours

      - run: git config user.email "nick@wylynko.com"
      - run: git config user.name "Nick Wylynko Bot"

      - run: npx bumpp@9.0.0 patch -y --no-push

      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Nick Wylynko Bot
          author_email: nick@wylynko.com
          message: 'Updated badges json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}